export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const DELETED_ITEM_REQUEST = 'DELETED_ITEM_REQUEST';
export const DELETED_ITEM_SUCCESS = 'DELETED_ITEM_SUCCESS';